### ISSUE TITLE
whether `temporal_interp` is used at training time ?

### ISSUE THREAD

**Issue by Dawn-LX** [subin-kim-cv/NVP#2]
Hi, thank you for the amazing work.

I'm interested in the temporal interpolation (frame interpolation) function of NVP. But I found that the quality of interpolated frames is very low.

I noted that if temporal interpolation is required (i.e., `opt.t_interp != -1`), then  `temporal_interp` is set as `True` at test time, and the model will call `self.sparse_grid.forward_inter`. But at training time, the `temporal_interp` is set as `Flase` as default.

So, do I need to turn on `temporal_interp` at training time if I want temporal interpolation ? or the `sparse_grid.forward_inter` is only used for inference time ?

**Comment by Dawn-LX** [comment]
> Hi, thank you for the amazing work.
> 
> I'm interested in the temporal interpolation (frame interpolation) function of NVP. But I found that the quality of interpolated frames is very low.
> 
> I noted that if temporal interpolation is required (i.e., `opt.t_interp != -1`), then `temporal_interp` is set as `True` at test time, and the model will call `self.sparse_grid.forward_inter`. But at training time, the `temporal_interp` is set as `Flase` as default.
> 
> So, do I need to turn on `temporal_interp` at training time if I want temporal interpolation ? or the `sparse_grid.forward_inter` is only used for inference time ?

Update: 

but when I set `temporal_interp=True` at training time, the loss and psnr are `nan`

**Comment by subin-kim-cv** [comment]
The `sparse_grid.forward_inter` is only used for inference time. 
You can get the temporally interpolated video as shown on the [homepage](https://subin-kim-cv.github.io/NVP/)
